### ISSUE TITLE
[Feat]: Scroll to top

### ISSUE THREAD

**Issue by pavitrachavda97** [JasonDsouza212/free-hit#1344]
### What feature?

Scroll to top button allows users to quickly navigate to the top of a page with a single click or tap. It offers a convenient way to return to the beginning of a long webpage without manually scrolling.

### Add screenshots

Button will added at a point where circle is located, below screen mode button
![image](https://github.com/JasonDsouza212/free-hit/assets/91004608/2e83a684-9d52-4004-a751-acaebdcc9a90)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JasonDsouza212** [comment]
@pavitrachavda97, there used to be a scroll-to-top button, but it seems to be missing now due to some error. Please fix that bug. Additionally, work on the positioning of the dark and light theme buttons along with the scroll-to-top button, ensuring that all three align in the same line across all widths.

**Comment by pavitrachavda97** [comment]
Okay. I will fix this bug and make sure to align this two button in same line across all width.
