### ISSUE TITLE
Finding the right tool

### ISSUE THREAD

**Issue by Gautam-666** [JasonDsouza212/free-hit#99]
**Is your feature request related to a problem? Please describe.**
When you open the website there is too much of resources available . It hard for people to find tools which they want to use.

**Describe the solution you'd like**
Above problem can be solved by adding a search bar in the top by replacing links of social with a search bar and putting social in the footer

**Describe alternatives you've considered**
Another method can be to sort the list of tools in alphabetical order so that people can look for their required tool. 

**Additional context**

**Comment by JasonDsouza212** [comment]
Thanks for the suggestion, @Gautam-666  It may be helpful to many people, and we'll definitely try to implement it as soon as possible

**Comment by JasonDsouza212** [comment]
@Gautam-666 Would you like to work on this?

**Comment by Gautam-666** [comment]
Yeah ...you can assign me on this..i will be more then happy to contribute

**Comment by itsarraj** [comment]
Problem : if people don't know what tool they need ,
solution : need to add some tags with each tools , 

p: if we sort in alphabetical order that wont solve the problem 
s: we should make a sort option to
 - sort in accending 
 - sort in decending 
 - sort by popularity ( default )
 - sort by date released 
 - sort by added (in website)
 
 and many more options for people to find tools
 
 note - search option will do no good because they can seach on goole than prefer this site , we have to solve problem by categorize the toold based on thier use and we should give brief description that where we can use this tool .

**Comment by Gautam-666** [comment]
Ohk ..i will try to complete it till tomorrow

**Comment by JasonDsouza212** [comment]
ok

**Comment by JasonDsouza212** [comment]
@Gautam-666  I have created a branch called 'sort'. It implements ascending and descending sorting, and everything looks good. If you want to work on it, start by using the 'sort' branch

**Comment by Gautam-666** [comment]
maybe you can close this issue as well....if the task is served.
